stages:
  - build
  - test
  - gitlab-utils
  - release

variables:
  DOCKER_DRIVER: overlay2
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  CI_APPLICATION_TAG: $CI_COMMIT_SHA
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  PIPENV_VENV_IN_PROJECT: "1"
  PYTHONUNBUFFERED: "1"

cache:
  paths:
    - .cache/pip
    - .venv

.python_template: &python_template
  image: python:3.6
  before_script:
    - pip install pipenv
    - pipenv install --dev --deploy --extra-index-url ./wheels
    - pipenv clean
    - pipenv graph
    - pipenv run pip freeze
  dependencies:
    - build-wheel

################################# Jobs follow #################################

build-wheel:
  image: python:3.6
  stage: build
  script:
    - python3 setup.py sdist
    - pip wheel --wheel-dir ./wheels .
  artifacts:
    paths:
      - ./wheels

mypy:
  <<: *python_template
  stage: test
  script:
    - pipenv run mypy .

black:
  <<: *python_template
  stage: test
  script:
    - pipenv run black --check --diff .

flake8:
  <<: *python_template
  stage: test
  script:
    - pipenv run flake8 .

isort:
  <<: *python_template
  stage: test
  script:
    - pipenv run isort --check-only -r .

pipenv-check:
  <<: *python_template
  stage: test
  script:
    - pipenv check

tests:
  <<: *python_template
  stage: test
  script:
    - apt-get update
    - apt-get install libarchive13  # Needed for diffoscope
    - pipenv run pytest .


release-pypi-master:
  <<: *python_template
  stage: release
  only:
    - master
  script:
    - export TWINE_TEST_USERNAME="${CI_PYPI_USER}"
    - export TWINE_TEST_PASSWORD="${CI_TEST_PYPI_PASSWORD}"
    - pipenv run python3 support/release.py


release-pypi-tag:
  <<: *python_template
  stage: release
  only:
    - tags
  script:
    - export TWINE_USERNAME="${CI_PYPI_USER}"
    - export TWINE_PASSWORD="${CI_PYPI_PASSWORD}"
    - pipenv run python3 support/release.py


pages:
  <<: *python_template
  stage: release
  allow_failure: true
  only:
    - master
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
    - public
