stages:
  - build
  - test
  - gitlab-utils
  - release

variables:
  DOCKER_DRIVER: overlay2
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  CI_APPLICATION_TAG: $CI_COMMIT_SHA
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  PIPENV_VENV_IN_PROJECT: "1"
  PYTHONUNBUFFERED: "1"

cache:
  paths:
    - .cache/pip
    - .venv

.python_template: &python_template
  image: python:3.6
  before_script:
    - pip install pipenv
    - pipenv install --dev --deploy --extra-index-url ./wheels
    - pipenv clean
    - pipenv graph
    - pipenv run pip freeze
  dependencies:
    - build-wheel

################################# Jobs follow #################################

build-wheel:
  image: python:3.6
  stage: build
  script:
    - python3 setup.py sdist
    - pip wheel --wheel-dir ./wheels .
  artifacts:
    paths:
      - ./wheels

build-docker:
  image: docker:stable
  stage: build
  only:
    - master
    - tags
  services:
    - docker:stable-dind
  variables:
  before_script:
    - apk add -U git
    - docker login -u $CI_DEPLOY_RW_USER -p $CI_DEPLOY_RW_PASSWORD $CI_REGISTRY
    - export PREVIOUS_APPLICATION_TAG=$(git rev-parse HEAD~1) || true
    - docker pull $CI_REGISTRY_IMAGE:master $CI_REGISTRY_IMAGE:latest || true
    - docker pull $CI_APPLICATION_REPOSITORY:$PREVIOUS_APPLICATION_TAG || true
  script:
    - docker build
        --cache-from=$CI_APPLICATION_REPOSITORY:{master,latest,$PREVIOUS_APPLICATION_TAG}
        --tag=$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
        .
    - docker push $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG

mypy:
  <<: *python_template
  stage: test
  script:
    - pipenv run mypy .

black:
  <<: *python_template
  stage: test
  script:
    - pipenv run black --check --diff .

flake8:
  <<: *python_template
  stage: test
  script:
    - pipenv run flake8 .

isort:
  <<: *python_template
  stage: test
  script:
    - pipenv run isort --check-only -r .

pipenv-check:
  <<: *python_template
  stage: test
  script:
    - pipenv check

reproducable-builds:
  <<: *python_template
  stage: test
  script:
    - apt-get update
    - apt-get install libarchive13
    - rm -fr .test-cache tests/reproducable.lock.toml
    - pipenv run matomo-dl --cache=./.test-cache update tests/reproducable.toml
    - cp tests/reproducable.lock.toml .test-cache/
    - pipenv run matomo-dl --cache=./.test-cache build tests/reproducable.toml --output ./.test-cache/reproducable-1.tar.gz
    - pipenv run matomo-dl --cache=./.test-cache build tests/reproducable.toml --output ./.test-cache/reproducable-2.tar.gz
    # Diffoscope is like diff on steroids.
    - pipenv run diffoscope --text-color=always --output-empty ./.test-cache/reproducable-{1,2}.tar.gz
    # Test that it works even without a cache
    - pipenv run matomo-dl --cache-level=none    build tests/reproducable.toml --output ./.test-cache/reproducable-3.tar.gz
    - pipenv run diffoscope --text-color=always --output-empty ./.test-cache/reproducable-{2,3}.tar.gz
  artifacts:
    paths:
      - .test-cache
    expire_in: 1 day


release-docker-master:
  image: docker:stable
  stage: release
  only:
    - master
  services:
    - docker:stable-dind
  before_script:
    - docker login -u $CI_DEPLOY_RW_USER -p $CI_DEPLOY_RW_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
    - docker tag $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG $CI_REGISTRY_IMAGE:master
    - docker push $CI_REGISTRY_IMAGE:master

release-docker-tag:
  image: docker:stable
  stage: release
  only:
    - tags
  services:
    - docker:stable-dind
  before_script:
    - docker login -u $CI_DEPLOY_RW_USER -p $CI_DEPLOY_RW_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
    - docker tag $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

release-pypi-master:
  <<: *python_template
  stage: release
  only:
    - master
  script:
    - export TWINE_USERNAME="${CI_PYPI_USER}"
    - export TWINE_PASSWORD="${CI_PYPI_PASSWORD}"
    - export TWINE_TEST_PASSWORD="${CI_TEST_PYPI_PASSWORD}"
    - pipenv run python3 support/release.py

pages:
  <<: *python_template
  stage: release
  allow_failure: true
  only:
    - master
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
    - public
