# version = "*"
version = "3.*"
# version = "~=3.5"

# license_key = "abcdef..."
# license_key = "$my_license_env"
# license_key = "<./my_license_file"
license_key = "<./license_key.txt"

[plugins]
AbTesting = "*"
ActivityLog = "*"
CustomDimensions = "*"
CustomAlerts = "*"
CustomReports = "*"
FormAnalytics = "*"
Funnels = "*"
HeatmapSessionRecording = "*"
MultiChannelConversionAttribution = "*"
MarketingCampaignsReporting = "*"
MediaAnalytics = "*"
QueuedTracking = "*"
RollUpReporting = "*"
SearchEngineKeywordsPerformance = "*"
UsersFlow = "*"
IP2Location = "*"

# [plugins.SiteCreationAutomation]
# git = "https://gitlab.wgtn.cat-it.co.nz/elearning/SiteCreationAutomation.git"
# ref = "master"

[customisation.manifest]
regenerate=true

[customisation.remove]
example_plugins=true
vendored_extras=true
documentation=true
build_support=true
tests=true
git_support=true
marketplace = true
professional_services = true

[customisation.update]
cacert=true

# [customisation.plugins_installed]
# add_plugins = true
# add_installed = true
