distribution_hash = "sha256:7bade4b8cc9b5fa3ea23965082ca99173d444a9fd9cdfbe7746e8685c940bb68"

[matomo]
version = "3.6.1"
link = "https://builds.matomo.org/matomo-3.6.1.zip"
hash = "sha256:76b0e92662a8e4f80b2722aedc9ae1afbd54340ce8a3895576bc96d745ffe47d"
extraction_root = "matomo/"

[plugin_locks.AbTesting]
extraction_root = "AbTesting/"
version = "3.2.4"
link = "https://plugins.matomo.org/api/2.0/plugins/AbTesting/download/3.2.4"
hash = "sha256:6cf03abaad6711d92a72cda2afc4da28ebc1b81636daa8191b4dc0c9cfea3225"

[plugin_locks.ActivityLog]
extraction_root = "ActivityLog/"
version = "3.2.1"
link = "https://plugins.matomo.org/api/2.0/plugins/ActivityLog/download/3.2.1"
hash = "sha256:e53ed1d050dacb506592802e2b76cd5ce4ff09387710b5f1207c41893cdcef49"

[plugin_locks.CustomDimensions]
extraction_root = "CustomDimensions/"
version = "3.1.3"
link = "https://plugins.matomo.org/api/2.0/plugins/CustomDimensions/download/3.1.3"
hash = "sha256:9bb18729b4f0d49d22fb1dcab76f9940a40d6beb3995889d3f5b1585bf7d35af"

[plugin_locks.CustomAlerts]
extraction_root = "CustomAlerts/"
version = "3.0.4"
link = "https://plugins.matomo.org/api/2.0/plugins/CustomAlerts/download/3.0.4"
hash = "sha256:d6c87c8be3fe025e60db56a104971157ff23e1c61747582f4cd251165995d615"

[plugin_locks.CustomReports]
extraction_root = "CustomReports/"
version = "3.1.3"
link = "https://plugins.matomo.org/api/2.0/plugins/CustomReports/download/3.1.3"
hash = "sha256:11d763e51473a17dc1c2cfec377b96f9474ddd9ffeed90c8ef16c13c4f1bbfab"

[plugin_locks.FormAnalytics]
extraction_root = "FormAnalytics/"
version = "3.1.8"
link = "https://plugins.matomo.org/api/2.0/plugins/FormAnalytics/download/3.1.8"
hash = "sha256:d87461d384413b22cd691a7ea99b801b9ae6ae91f2e2f0f3e5dcf0b14fc2e095"

[plugin_locks.Funnels]
extraction_root = "Funnels/"
version = "3.1.8"
link = "https://plugins.matomo.org/api/2.0/plugins/Funnels/download/3.1.8"
hash = "sha256:d1b6a3a51326a0c8709fdd04a6da8fd144a443a8d9e915c53ebcbdce02f2d703"

[plugin_locks.HeatmapSessionRecording]
extraction_root = "HeatmapSessionRecording/"
version = "3.2.12"
link = "https://plugins.matomo.org/api/2.0/plugins/HeatmapSessionRecording/download/3.2.12"
hash = "sha256:aab3edbc6fcd6ada0ce631473d144db41d83304eec01e5f53544a727d2baee1d"

[plugin_locks.MultiChannelConversionAttribution]
extraction_root = "MultiChannelConversionAttribution/"
version = "3.0.3"
link = "https://plugins.matomo.org/api/2.0/plugins/MultiChannelConversionAttribution/download/3.0.3"
hash = "sha256:53a3b73e0471c7eb1f242f063e7fbfe641eb1bebe0f3c774994526b4f934123c"

[plugin_locks.MarketingCampaignsReporting]
extraction_root = "MarketingCampaignsReporting/"
version = "3.1.1"
link = "https://plugins.matomo.org/api/2.0/plugins/MarketingCampaignsReporting/download/3.1.1"
hash = "sha256:bfdb6952293bc11cb579cafff5a8cc2424203fa823fede3d2d0b30cfb6c4c8d9"

[plugin_locks.MediaAnalytics]
extraction_root = "MediaAnalytics/"
version = "3.2.10"
link = "https://plugins.matomo.org/api/2.0/plugins/MediaAnalytics/download/3.2.10"
hash = "sha256:43bfd121ad7f40dc50849697e9d31b846054159cb2ab0cc89f04799b7b113d63"

[plugin_locks.QueuedTracking]
extraction_root = "QueuedTracking/"
version = "3.3.1"
link = "https://plugins.matomo.org/api/2.0/plugins/QueuedTracking/download/3.3.1"
hash = "sha256:06c7d9ef2f4581ddaa13dcc12beae6b86db9b6549eb54a8e79176d8271fd570b"

[plugin_locks.RollUpReporting]
extraction_root = "RollUpReporting/"
version = "3.2.2"
link = "https://plugins.matomo.org/api/2.0/plugins/RollUpReporting/download/3.2.2"
hash = "sha256:8284327518168677f68e1e08d36cab7d11409fd346de4cbab50e3e173f404e4c"

[plugin_locks.SearchEngineKeywordsPerformance]
extraction_root = "SearchEngineKeywordsPerformance/"
version = "3.2.3"
link = "https://plugins.matomo.org/api/2.0/plugins/SearchEngineKeywordsPerformance/download/3.2.3"
hash = "sha256:22685f1ef7c989169a4027943c929292a4dafac23021b8755d8f22c7a0ccaf80"

[plugin_locks.UsersFlow]
extraction_root = "UsersFlow/"
version = "3.1.7"
link = "https://plugins.matomo.org/api/2.0/plugins/UsersFlow/download/3.1.7"
hash = "sha256:f27b35bd8f499c57bc8d70185fb7d35571d28cfd49656eb25bac4f71e4f4e14a"

[plugin_locks.IP2Location]
extraction_root = "IP2Location/"
version = "3.1.8"
link = "https://plugins.matomo.org/api/2.0/plugins/IP2Location/download/3.1.8"
hash = "sha256:650e51b76c3ee4119cb96fc20f152c031919e7400ae08e7ff17288e5903270c0"
